### ISSUE TITLE
LoginScreen() splashes on reopening the app.

### ISSUE THREAD

**Issue by udaykhalsa** [sbis04/sign_in_flutter#10]
Maybe it takes the app for a while to know the state or what. But whenever the app is reopened the LoginScreen() splashes for a second then redirects to FirstScreen() if the user is logged in.

**Comment by sbis04** [comment]
This won't be such a problem in the **release** build of the app. 

But if you still think this is a problem then you can follow the steps below.

1. Declare a variable to track whether it has completed retrieving the user:
   ```dart
   bool _isRetrievingUser = true;
   ```
2. Update the `getUserInfo()` method to this:

```dart
  Future getUserInfo() async {
    await getUser();
    setState(() {
      _isRetrievingUser = false;
    });
    print(uid);
  }
```
3. Finally, in the `MaterialApp` home:
```dart
_isRetrievingUser
          ? Container()
          : (uid != null && authSignedIn != false)
              ? ProfileScreen()
              : LoginPage(),
```

**Comment by sbis04** [comment]
Closing this issue. @udaykhalsa you can open this again if you need any further help.
