### ISSUE TITLE
FirebaseCore/Sources/Private/FirebaseCoreInternal.h  file not found

### ISSUE THREAD

**Issue by lizhaobomb** [sbis04/sign_in_flutter#13]
hi @sbis04 when i run the project for ios i get this error，
the flutter doctor is ok

can you give me some suggestions, thanks in advance

sign_in_flutter-master/ios/Pods/FirebaseAuth/FirebaseAuth/Sources/User/FIRUser.m:20:9: fatal error: 'FirebaseCore/Sources/Private/FirebaseCoreInternal.h' file not found
#import "FirebaseCore/Sources/Private/FirebaseCoreInternal.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by sbis04** [comment]
I have updated the project to the latest **Podfile** specs. Please try to run now.

**Comment by sbis04** [comment]
Assuming this issue to be solved. Closing it.
