### ISSUE TITLE
Firebase Auth doesnt work

### ISSUE THREAD

**Issue by sohailg** [sbis04/sign_in_flutter#14]
Running "flutter pub get" in xyz
![Screenshot from 2020-07-15 21-20-59](https://user-images.githubusercontent.com/28216209/87567126-8b959a00-c6e1-11ea-87e1-fa8d08b73554.png)
     
The current Flutter SDK version is 1.12.13.

Because flutter_simple_slider depends on firebase_auth >=0.15.2 which requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0, version solving failed.
pub get failed (1; Because flutter_simple_slider depends on firebase_auth >=0.15.2 which requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0, version solving failed.)
Process finished with exit code 1

**Comment by sbis04** [comment]
You will need to update the **Flutter SDK version** in the `environment` -> `sdk` in your `pubspec.yaml` file

**Comment by sbis04** [comment]
Assuming this to be solved. Closing it.
