### ISSUE TITLE
Null User After Account Select on Android

### ISSUE THREAD

**Issue by jeremyw24** [sbis04/sign_in_flutter#16]
I am experiencing a weird issue on Android Devices.

When Android users open the app (I created a build and sent them the APK, not via Play store), and click the Sign In button they are presented with a list of accounts they are currently signed into, this includes their G Suite Domain Account and potentially personal accounts.

![image](https://user-images.githubusercontent.com/4019090/93833635-809c4e80-fcbc-11ea-9a70-2542bef56989.png)
Note: First account is personal Gmail second account is a domain account.

When selecting the domain account, the user passes authentication and lands at the designated home screen where it should display the users first name, when this bug is experienced the first name returns Null. 

![image](https://user-images.githubusercontent.com/4019090/93833954-8f373580-fcbd-11ea-9848-197648e93a28.png)

```
SizedBox(height: 10),
                  Padding(
                    padding: EdgeInsets.fromLTRB(20, 0, 20, 0),
                    child: Text(
                      "G'Day $firstName",
                      textAlign: TextAlign.center,
                      style: TextStyle(
                          color: Colors.black,
                          fontStyle: FontStyle.normal,
                          fontWeight: FontWeight.bold,
                          fontSize: 20),
                    ),
                  ),
```

It would appear at this stage the user is actually not Authenticated but IS able to use the app as normal. 

Secondly, the API should be scoped for internal use only to our domain, but does allow any Google user to authenticate, resulting in the same issue as above.

I can not reproduce this issue on iOS Devices, only Android and largely Android 10.

**Comment by jeremyw24** [comment]
Update: I have changed the sign in call to your updated version:
```
signInWithGoogle().then((result) {
          if (result != null) {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) {
                  return HomeView();
                },
              ),
            );
          }
        });
```

This now prevents the use of personal accounts. However, I am getting two distinct behaviors on AVD and a Physical Device.

AVD:
- Restricts personal accounts and returns to login_page (expected)
- Selecting domain account allows user to auth and returns firstName (expected)

Physical Device:
- Restricts personal accounts and returns to login_page (expected)
- Selecting domain account returns to login_page (not expected)

I am unable to recreate the issue from the physical device on AVD.

**Comment by sbis04** [comment]
Track the updates on this new repo (using Flutter 2.0): https://github.com/sbis04/flutterfire-samples

This repo will be archived soon.
