### ISSUE TITLE
Add network connectivity check

### ISSUE THREAD

**Issue by sbis04** [sbis04/sign_in_flutter#2]
## Objectives

* Add a network connectivity check before showing the **Login Screen**.
* Add a new screen, which will show when there is no network connection.

## Follow these steps for contributing:

1. Fork this repo.
2. Clone it to your local system.
3. Add new files or modify files by creating a **new branch** named "**network_check**".
4. Then **commit** and **push** it.
5. Now, create a **Pull Request**.

**NOTE: Please create a new branch before start working, from the master branch. Otherwise, your PR will be rejected.** 

‣ You are free to add animations (**Flare animations are preferred**) & illustrations. You are free to show as much UI design creativity as you want.

‣ You should also add comments wherever necessary.

**Comment by StrangeNoob** [comment]
hey is this issue taken/assign if not ? I would love work on it !!

**Comment by sbis04** [comment]
Yes, you can start working on it.

**Comment by StrangeNoob** [comment]
can you provide me the json file ? Because there is a build error.
