### ISSUE TITLE
For Test run its Fails 

### ISSUE THREAD

**Issue by sabarinathancs** [sbis04/sign_in_flutter#6]
![WhatsApp Image 2019-12-26 at 1 39 19 AM](https://user-images.githubusercontent.com/5072200/71450102-f650a980-2780-11ea-8414-7603bed694e2.jpeg)

**Comment by daniele777** [comment]
How to solve?

**Comment by vpxoxo** [comment]
got the same error here, seems like there is something wrong with the google profile image URL?

**Comment by vpxoxo** [comment]
Hi I found that in sign_in.dart, these should be used. 

`Future<FirebaseUser> signInWithGoogle() async {`

`  return user;`

also i commented out the circular avatar part for the image in the login page because it didn't work

hope this helps!!

**Comment by daniele777** [comment]
You solve this issue ?

**Comment by vpxoxo** [comment]
Yes it works for me now using the above method. 👍🏻

**Comment by daniele777** [comment]
How ?? Need to add only return ??

Il gio 27 feb 2020, 07:23 vpxoxo <notifications@github.com> ha scritto:

**Comment by vpxoxo** [comment]
I mean do the following two changes:  

change this
https://github.com/sbis04/sign_in_flutter/blob/5ad9067111942c1dff253e056456ce2f1d91ca4b/lib/sign_in.dart#L31
to this
`Future<FirebaseUser> signInWithGoogle() async {`

and change this
https://github.com/sbis04/sign_in_flutter/blob/5ad9067111942c1dff253e056456ce2f1d91ca4b/lib/sign_in.dart#L64
to this
`return user;`

**Comment by daniele777** [comment]
Thank you !!!!

**Comment by vpxoxo** [comment]
no prob!!

**Comment by sbis04** [comment]
Thanks @vpxoxo for solving this issue. 🎉
