### ISSUE TITLE
signInWithGoogle().whenComplete is triggered whether or not the login succeeds

### ISSUE THREAD

**Issue by pgainullin** [sbis04/sign_in_flutter#8]
which seems to be the expected behaviour of whenComplete: 

"Registers a function to be called when this future completes.
The [action] function is called when this future completes, whether it does so with a value or with an error."

changing the signInWithGoogle() to return the user and then rewriting as follows seems to do the trick:

```
        signInWithGoogle().then((user) {
          if (user != null) {
            Navigator.of(context).push(
              MaterialPageRoute(
                builder: (context) {
                  return [...]();
                },
              ),
            );
          }

```

**Comment by daniele777** [comment]
Where i can implement this part? i have this type of issue
![Screenshot_20200504-113117](https://user-images.githubusercontent.com/8341788/80953079-1d884900-8dfb-11ea-90fa-404030e9a27a.png)

**Comment by pgainullin** [comment]
https://github.com/sbis04/sign_in_flutter/blob/5ad9067111942c1dff253e056456ce2f1d91ca4b/lib/login_page.dart#L56 <<this line

however your issue is potentially unrelated and could occur because the user metadata does not contain a picture URL (presumably triggered here - https://github.com/sbis04/sign_in_flutter/blob/5ad9067111942c1dff253e056456ce2f1d91ca4b/lib/first_screen.dart#L44)

**Comment by daniele777** [comment]
Same error i can't return in login screen with crediential of google accont.... idea?

**Comment by pgainullin** [comment]
a bit hard to say especially not seeing the actual logs for the error (from the Run tab or Logcat). 

try commenting out the whole section using Image.network here - https://github.com/sbis04/sign_in_flutter/blob/5ad9067111942c1dff253e056456ce2f1d91ca4b/lib/first_screen.dart#L42-L48

**Comment by daniele777** [comment]
Authentication good i retrive link of my photo and name and email..but still have problem..

A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'

**Comment by chrisbinsunny** [comment]
This problem still exists. I guess providing a FutureBuilder can solve the issue. If anyone knows how to solve this, please help.

**Comment by sbis04** [comment]
I have fixed this issue. Please check out the latest **master** branch of this repo. Refer: https://github.com/sbis04/sign_in_flutter/commit/ad503dc100f7e0fcbf9b49145f47bbb97dc7d136

Closing
